### ISSUE TITLE
希望老师能编译成java客户端

### ISSUE THREAD

**Issue by wjl110** [binganao/TaiO#5]
很有潜力的项目

**Comment by binganao** [comment]
这个项目将在一星期后开始重构，当时没有考虑好子节点的问题，开发到一半发现可能弄成分布式会比较合适。最近没有什么时间做，应该一星期后事情少了会继续开发。Golang可以直接编译成二进制文件，到时候会分发不同操作系统和处理器架构的Release版本。

**Comment by wjl110** [comment]
🎉🎉🎉
